FLASK_APP=run.py
FLASK_DEBUG=1
SECRET_KEY=gardensnotlawns
ENVIRONMENT=develop

DEV_HOST=aws.connect.psdb.cloud
DEV_DATABASE=ufarms-dev
DEV_USERNAME=h5m7t0los20sgj8xf4h0
DEV_PASSWORD=pscale_pw_xzOB3JDsvi1ZfTmYoXo8q6UhI3FMvrVemL895Uip5md

PROD_HOST=aws.connect.psdb.cloud
PROD_DATABASE=ufarms-dev
PROD_USERNAME=hkm48whtc5aegmpf6lvi
PROD_PASSWORD=pscale_pw_OIw2Zz7IirEnQ9a1eKAaCd9wMo209L3OeeAK5FK8OLP