FLASK_APP=run.py
FLASK_DEBUG=1
SECRET_KEY=gardensnotlawns
ENVIRONMENT=develop
MAPBOX_TOKEN=pk.eyJ1IjoibWFya2VobGVyIiwiYSI6ImNsbzdpYmpnczA1MDcya3Rqc3hham9nYzMifQ.bkhIBBUVZxA9pnaqFM4p-g

DEV_HOST=aws.connect.psdb.cloud
DEV_DATABASE=ufarms-dev
DEV_USERNAME=gvhz3tkpqgr8ckva3r32
DEV_PASSWORD=pscale_pw_W8VE5HLPRTX0jNFjf5ZFZF3jPTNBonWEmD15SBogc0V

PROD_HOST=aws.connect.psdb.cloud
PROD_DATABASE=ufarms-dev
PROD_USERNAME=hkm48whtc5aegmpf6lvi
PROD_PASSWORD=pscale_pw_OIw2Zz7IirEnQ9a1eKAaCd9wMo209L3OeeAK5FK8OLP