CREATE TABLE UfarmsBadges (
    BadgeID INT PRIMARY KEY AUTO_INCREMENT,
    BadgeName VARCHAR(55) UNIQUE,
    UfarmID --foriegn key
    Description TEXT,
    Image VARBINARY(MAX),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);